-- Seed Career Paths Part 3 — mapped to actual schema

INSERT INTO public.career_paths (
  domain, title, slug, description, overview,
  salary_entry, salary_mid, salary_senior,
  perks, impact, exposure, eligibility,
  skills_needed, upsc_skill_mapping, difficulty_rating, growth_rate,
  courses, certifications, portfolio_projects, launchpad_weeks,
  estimated_cost, how_to_apply, youtube_links, podcast_links,
  linkedin_groups, professional_associations, is_active
) VALUES

-- 1. Regulatory Affairs Specialist
(
  'Policy, Governance & Public Affairs',
  'Regulatory Affairs Specialist',
  'regulatory-affairs-specialist',
  'Navigate complex regulatory frameworks for pharma, fintech, or telecom companies.',
  'Regulatory Affairs Specialists help companies comply with government regulations. Ex-UPSC aspirants with policy knowledge are highly valued in pharma, fintech, and telecom sectors where navigating regulatory frameworks is critical. You act as a bridge between government bodies and corporates.',
  '₹8 LPA', '₹18 LPA', '₹35 LPA',
  ARRAY['Flexible hours in senior roles', 'Exposure to government functioning', 'Industry conferences', 'Performance bonuses'],
  'Ensure products and services reach citizens safely and legally. Your work directly shapes how regulations protect public health and commerce.',
  'Regular interaction with CDSCO, TRAI, SEBI, and MoHFW. Represent companies at regulatory hearings.',
  'Graduate in Science, Law, or Commerce; LLB or MBA preferred',
  ARRAY['Policy analysis', 'Regulatory writing', 'Stakeholder management', 'Compliance auditing', 'Government relations', 'Legal drafting'],
  'High overlap with GS Paper 2 (Governance, Polity), Law optional, and Public Administration optional. Overlap Score: 85%',
  3, 'High',
  '[{"title": "Regulatory Affairs Fundamentals", "provider": "RAPS", "url": "https://www.raps.org/learning/courses/regulatory-fundamentals", "free": false}, {"title": "Compliance & Regulatory Management", "provider": "Coursera (Duke)", "url": "https://www.coursera.org/specializations/compliance", "free": false}]'::jsonb,
  ARRAY['RAC (Regulatory Affairs Certification) by RAPS', 'PG Diploma in Regulatory Affairs (NIPER)'],
  ARRAY['Prepare a mock CDSCO drug license application dossier', 'Write a regulatory risk assessment for a hypothetical fintech product', 'Analyze a recent SEBI enforcement order and summarize compliance gaps'],
  '[{"week": 1, "focus": "Sector selection", "tasks": ["Choose pharma/fintech/telecom based on your optional subject", "Read key regulatory acts (Drugs Act, FSSAI, TRAI)", "Follow MoHFW, SEBI, TRAI circulars"]}, {"week": 2, "focus": "Regulatory writing", "tasks": ["Draft a mock compliance report", "Read 5 actual regulatory submission documents", "Learn CTD dossier format"]}, {"week": 3, "focus": "Networking", "tasks": ["Connect with RA professionals on LinkedIn", "Join RAPS India chapter", "Attend a FICCI Health webinar"]}, {"week": 4, "focus": "Application", "tasks": ["Apply to pharma/fintech startups for RA associate roles", "Prepare case study: how to obtain a drug license in India", "Apply to RAPS Regulatory Foundations Certificate"]}]'::jsonb,
  '₹5,000–₹50,000 (certifications)',
  'Apply via LinkedIn Jobs, Naukri, and IIMJobs. Target Sun Pharma, Dr. Reddy''s, Cipla, Razorpay, Airtel.',
  '[{"title": "Regulatory Affairs India - CDSCO Overview", "channel": "Pharma Careers", "url": "https://youtube.com"}, {"title": "How to Break into Regulatory Affairs", "channel": "RA Careers", "url": "https://youtube.com"}]'::jsonb,
  '[{"title": "The Compliance Advantage", "platform": "Spotify", "url": "https://spotify.com"}]'::jsonb,
  '[{"name": "Regulatory Affairs Professionals India", "url": "https://linkedin.com"}, {"name": "FSSAI Regulatory Network", "url": "https://linkedin.com"}]'::jsonb,
  ARRAY['RAPS (Regulatory Affairs Professionals Society)', 'FSSAI India'],
  TRUE
),

-- 2. Judiciary Preparation (PCS-J)
(
  'Law & Legal Services',
  'Judiciary Preparation (PCS-J)',
  'pcs-j-judiciary',
  'Transition your UPSC preparation to crack state judicial services exams.',
  'Provincial Civil Services (Judicial) exams are a natural pivot for UPSC aspirants who studied law. The preparation overlap is significant — polity, law, and essay writing all transfer directly. PCS-J leads to becoming a Civil Judge / Munsiff, with a structured promotion ladder to District Judge and High Court.',
  '₹7 LPA', '₹14 LPA', '₹22 LPA',
  ARRAY['Government job security', 'Housing & transport allowance', 'Pension', 'Judicial discretion and authority'],
  'Deliver justice to thousands of citizens at the grassroots level. Reduce pendency in India''s overburdened courts.',
  'Regular court proceedings, interaction with lawyers, district administration, and High Court supervision.',
  'LLB mandatory; LLM advantageous for academic track',
  ARRAY['Constitutional law', 'Civil Procedure Code', 'Criminal Procedure Code', 'Evidence Act', 'Legal drafting', 'Judgment writing'],
  'Direct overlap with Law optional, GS Paper 2 (Polity, Governance), and Essay. Overlap Score: 90%',
  4, 'Stable',
  '[{"title": "PCS-J Complete Course", "provider": "Judiciary Gold", "url": "https://www.judiciarygold.com", "free": false}, {"title": "CPC & CrPC for Judiciary", "provider": "Law Sikho", "url": "https://lawsikho.com", "free": false}]'::jsonb,
  ARRAY['State PCS-J (varies by state)', 'LLM (optional, for academic track)'],
  ARRAY['Write 5 model civil judgments on common disputes', 'Prepare a case brief for a landmark Supreme Court case', 'Draft a written statement for a sample civil suit'],
  '[{"week": 1, "focus": "Gap analysis", "tasks": ["Compare your state PCS-J syllabus with UPSC GS", "Identify law papers not yet studied (CPC, CrPC, Evidence Act)", "Get bare acts for CPC, CrPC, IPC, Evidence Act, TP Act"]}, {"week": 2, "focus": "Core law subjects", "tasks": ["Start CPC — jurisdiction, pleadings, written statement", "Practice judgment writing with model answers", "Study recent High Court judgments from your state"]}, {"week": 3, "focus": "Mock tests", "tasks": ["Take 2 full-length PCS-J prelim mocks", "Join an online PCS-J test series", "Revise constitutional law (strong from UPSC prep)"]}, {"week": 4, "focus": "Mains prep", "tasks": ["Write 3 practice judgments", "Solve previous year mains papers", "Connect with PCS-J qualifiers on LinkedIn"]}]'::jsonb,
  '₹10,000–₹30,000 (coaching & test series)',
  'Register via State Public Service Commission websites. Check eligibility (LLB + age limit) carefully per state.',
  '[{"title": "PCS-J Preparation Strategy for UPSC Aspirants", "channel": "Judiciary Gold", "url": "https://youtube.com/judiciaryprep"}, {"title": "Judgment Writing Masterclass", "channel": "Law Tutor India", "url": "https://youtube.com"}]'::jsonb,
  '[{"title": "The Legal Ladder", "platform": "Spotify", "url": "https://spotify.com"}, {"title": "Bar & Bench Podcast", "platform": "Apple Podcasts", "url": "https://podcasts.apple.com"}]'::jsonb,
  '[{"name": "PCS-J Aspirants India", "url": "https://t.me"}, {"name": "Judiciary Exam Prep", "url": "https://facebook.com"}]'::jsonb,
  ARRAY['State Public Service Commission', 'Judiciary Gold (coaching)'],
  TRUE
),

-- 3. ADR Specialist
(
  'Law & Legal Services',
  'Alternative Dispute Resolution (ADR) Specialist',
  'adr-specialist',
  'Resolve high-stakes disputes as a mediator or arbitrator — without the courtroom.',
  'ADR is booming in India as courts decongest. Mediators, arbitrators, and conciliators are in high demand in commercial disputes, family law, labour, and international trade. UPSC aspirants bring strong analytical thinking, neutrality, and policy awareness — ideal traits for ADR.',
  '₹10 LPA', '₹22 LPA', '₹50 LPA',
  ARRAY['High autonomy', 'Flexible/remote work', 'International arbitration opportunities', 'Prestigious empanelments'],
  'Reduce judicial burden while delivering faster, confidential justice to parties in dispute.',
  'Work with top law firms, corporates, and international institutions like ICC, DIAC, MCIA.',
  'LLB preferred; graduates with ADR certification also eligible',
  ARRAY['Negotiation', 'Active listening', 'Legal drafting', 'Arbitration law', 'Conflict resolution', 'Emotional intelligence'],
  'Overlap with Law optional (Arbitration & Conciliation Act), GS Paper 2 (Dispute resolution), and Essay writing skills. Overlap Score: 75%',
  3, 'High',
  '[{"title": "Mediation and Conflict Resolution", "provider": "Coursera (UC Irvine)", "url": "https://www.coursera.org/learn/mediation", "free": false}, {"title": "Arbitration Law in India", "provider": "Law Sikho", "url": "https://lawsikho.com/course/certificate-course-arbitration-law-practice", "free": false}, {"title": "Harvard Negotiation Essentials", "provider": "edX (Harvard)", "url": "https://www.edx.org/course/negotiation-mastery", "free": false}]'::jsonb,
  ARRAY['CIArb (Chartered Institute of Arbitrators) Membership', 'ICA Mediation Certification', 'ICADR Mediator Certification'],
  ARRAY['Write a mock arbitration award for a hypothetical commercial dispute', 'Draft a mediation settlement agreement', 'Comparative note on DIAC vs ICC arbitration rules'],
  '[{"week": 1, "focus": "ADR landscape", "tasks": ["Read the Arbitration and Conciliation Act 1996 (amended 2021)", "Study Mediation Bill 2023", "Watch 3 recorded mock mediations on YouTube"]}, {"week": 2, "focus": "Training enrollment", "tasks": ["Enroll in ICA or ICADR mediation certification (40-hour course)", "Practice role-play mediation with a partner", "Study Harvard Negotiation Project materials (free online)"]}, {"week": 3, "focus": "Institution empanelment", "tasks": ["Apply to DIAC, MCIA, or Delhi HC Mediation Centre", "Connect with CIArb India chapter", "Build ADR profile on LinkedIn"]}, {"week": 4, "focus": "Practice cases", "tasks": ["Volunteer for community mediation under a legal aid authority", "Write a case note on a recent Indian arbitration award", "Apply to law firms for in-house ADR roles"]}]'::jsonb,
  '₹15,000–₹80,000 (CIArb/ICA certification)',
  'Apply via IIMJobs, LinkedIn. Approach Trilegal, AZB & Partners, Cyril Amarchand for in-house ADR roles.',
  '[{"title": "Introduction to Arbitration in India", "channel": "Arbitration India", "url": "https://youtube.com"}, {"title": "Mediation Techniques for Beginners", "channel": "ADR Skills", "url": "https://youtube.com"}]'::jsonb,
  '[{"title": "Dispute Resolution India", "platform": "Spotify", "url": "https://spotify.com"}]'::jsonb,
  '[{"name": "ADR Practitioners India", "url": "https://linkedin.com"}, {"name": "CIArb India Network", "url": "https://linkedin.com"}]'::jsonb,
  ARRAY['CIArb India', 'Indian Council of Arbitration (ICA)', 'ICADR'],
  TRUE
),

-- 4. School / College Teacher
(
  'Education & Training',
  'Teacher / Lecturer (School & College)',
  'school-college-teacher',
  'Shape future generations — in classrooms from elite schools to government colleges.',
  'Teaching is one of the most respected transitions for UPSC aspirants. Deep subject expertise in history, polity, economics, or geography translates directly to school/college teaching. From elite private schools (20+ LPA) to government college lectureships via NET/SET, the path is well-defined and deeply meaningful.',
  '₹5 LPA', '₹14 LPA', '₹25 LPA',
  ARRAY['Summer vacations', 'Government pension (college)', 'Job security', 'Social respect and impact'],
  'Directly shape the intellectual development of India''s next generation. Inspire students who may go on to become the change-makers of tomorrow.',
  'Interact with students, parents, academic boards, and researchers. Build institutional knowledge over decades.',
  'Graduate + B.Ed for schools; Post-Graduate + NET/SET for colleges',
  ARRAY['Deep subject knowledge', 'Communication', 'Curriculum design', 'Pedagogy', 'Research writing', 'Classroom management'],
  'Direct overlap with any UPSC optional subject. GS depth useful for interdisciplinary teaching. Overlap Score: 80%',
  2, 'Stable',
  '[{"title": "B.Ed Distance Program", "provider": "IGNOU", "url": "https://www.ignou.ac.in/bed", "free": false}, {"title": "UGC-NET Preparation", "provider": "Unacademy", "url": "https://unacademy.com/goal/ugc-net", "free": false}, {"title": "Effective Teaching in Higher Education", "provider": "Coursera (Berkeley)", "url": "https://www.coursera.org/learn/effective-teaching", "free": false}]'::jsonb,
  ARRAY['B.Ed (Bachelor of Education)', 'UGC-NET / State SET', 'CTET (for central govt schools)'],
  ARRAY['Design a 5-lesson curriculum module for Class 12 Political Science', 'Create an educational YouTube video on a UPSC GS topic', 'Write a research paper draft for a UGC journal'],
  '[{"week": 1, "focus": "Track selection", "tasks": ["Decide: school (B.Ed route) vs college (NET route)", "Research IGNOU distance B.Ed program", "Check UGC-NET syllabus for your optional subject"]}, {"week": 2, "focus": "Demo classes", "tasks": ["Record a 20-minute demo class on a topic from your optional", "Upload to YouTube as unlisted for feedback", "Visit 3 nearby private schools to inquire about roles"]}, {"week": 3, "focus": "NET/SET preparation", "tasks": ["Solve 5 years of UGC-NET previous papers", "Join an online NET coaching group on Telegram", "Study Paper 1 (teaching aptitude + research methodology)"]}, {"week": 4, "focus": "Applications", "tasks": ["Apply to 5 private schools with your demo video link", "Register for the next UGC-NET exam cycle", "Connect with NET-qualified teachers on LinkedIn"]}]'::jsonb,
  '₹50,000–₹2,00,000 (B.Ed or coaching)',
  'Apply to private schools directly. For government colleges, clear UGC-NET/SET, then apply via NTA or state PSC portals.',
  '[{"title": "How to Become a Lecturer After UPSC", "channel": "Education Careers India", "url": "https://youtube.com"}, {"title": "UGC NET Study Strategy", "channel": "NET Prep Hub", "url": "https://youtube.com"}]'::jsonb,
  '[{"title": "The Educator Podcast", "platform": "Spotify", "url": "https://spotify.com"}]'::jsonb,
  '[{"name": "UGC-NET Aspirants India", "url": "https://t.me"}, {"name": "Teachers of India", "url": "https://facebook.com"}]'::jsonb,
  ARRAY['UGC India', 'NCTE (National Council for Teacher Education)'],
  TRUE
),

-- 5. Curriculum Designer
(
  'Education & Training',
  'Curriculum Designer / Instructional Designer',
  'curriculum-designer',
  'Design learning experiences that actually work — for schools, EdTech, or corporates.',
  'Curriculum designers shape what and how people learn. Ex-UPSC aspirants bring deep subject expertise, structured thinking, and an understanding of exam-oriented education — making them naturals for designing courses for EdTech platforms, schools, or corporate L&D teams.',
  '₹8 LPA', '₹16 LPA', '₹30 LPA',
  ARRAY['Remote-friendly', 'Creative work', 'High demand from EdTech boom', 'No fixed location required'],
  'Shape how millions of Indian learners access quality education, particularly via EdTech platforms serving tier-2 and tier-3 cities.',
  'Work with content creators, product managers, engineers, and subject matter experts at top EdTech companies.',
  'Graduate in any field; education/teaching background preferred',
  ARRAY['Instructional design', 'Learning management systems', 'Content writing', 'Assessment design', 'Storyboarding', 'Bloom''s Taxonomy', 'ADDIE model'],
  'UPSC optional subject depth is directly applicable. Writing skills from Mains. Analytical structuring from GS preparation. Overlap Score: 75%',
  2, 'High',
  '[{"title": "Instructional Design Fundamentals", "provider": "Coursera (UC San Diego)", "url": "https://www.coursera.org/learn/instructional-design-foundations", "free": false}, {"title": "Articulate 360 Free Trial", "provider": "Articulate", "url": "https://articulate.com/360/trial", "free": true}]'::jsonb,
  ARRAY['ATD Instructional Design Certificate', 'Google Certificate in Instructional Design', 'Articulate Storyline Certification'],
  ARRAY['Design a complete 4-week online course with syllabus, quizzes, and activities', 'Create a learning outcomes document for a Class 10 history unit', 'Audit an existing EdTech course and write a redesign proposal'],
  '[{"week": 1, "focus": "ID fundamentals", "tasks": ["Study ADDIE and Bloom''s Taxonomy", "Analyze the structure of 3 popular Coursera courses", "Read ''The Art of Explanation'' by Lee LeFever"]}, {"week": 2, "focus": "Portfolio course", "tasks": ["Design a mini 5-module course on a UPSC topic", "Use Canva or Google Slides for storyboards", "Write clear learning objectives for each module"]}, {"week": 3, "focus": "Tools", "tasks": ["Learn Articulate Rise or Moodle (free trials)", "Build one interactive lesson with quiz", "Study Khan Academy content structure"]}, {"week": 4, "focus": "Apply", "tasks": ["Upload portfolio to personal website or Google Drive", "Apply to BYJU''S, Unacademy, Scaler, upGrad", "Connect with instructional designers on LinkedIn"]}]'::jsonb,
  '₹0–₹20,000 (mostly free tools available)',
  'Apply via LinkedIn Jobs, IIMJobs, and AngelList India. Target BYJU''S, Unacademy, upGrad, Scaler, Khan Academy India.',
  '[{"title": "Instructional Design for Beginners", "channel": "Tim Slade", "url": "https://youtube.com/timslade"}, {"title": "EdTech India Career Guide", "channel": "EdTech Careers", "url": "https://youtube.com"}]'::jsonb,
  '[{"title": "The ID Chat Podcast", "platform": "Spotify", "url": "https://spotify.com"}]'::jsonb,
  '[{"name": "Instructional Design India", "url": "https://linkedin.com"}, {"name": "EdTech Professionals India", "url": "https://linkedin.com"}]'::jsonb,
  ARRAY['ATD (Association for Talent Development)', 'eLearning Guild India'],
  TRUE
),

-- 6. TV News Producer
(
  'Media, Journalism & Content',
  'TV News Producer / Researcher',
  'tv-news-producer',
  'Drive the stories behind the cameras — research, produce, and shape news narratives.',
  'TV news production requires exactly what UPSC prep builds: speed-reading, synthesis, understanding of governance and current affairs, and the ability to explain complexity in simple terms. News researchers and producers are the intellectual backbone of any newsroom.',
  '₹7 LPA', '₹15 LPA', '₹30 LPA',
  ARRAY['Fast-paced stimulating work', 'Access to newsmakers', 'On-the-ground reporting exposure', 'Press credentials'],
  'Shape public discourse and hold power accountable through quality journalism that serves millions of viewers.',
  'Work with reporters, anchors, guests, editors, and bureau chiefs across India and internationally.',
  'Graduate; PG Diploma in Journalism/Mass Communication preferred',
  ARRAY['Current affairs depth', 'Script writing', 'Fact-checking', 'Video editing basics', 'Editorial judgment', 'Speed and accuracy under pressure'],
  'Current affairs depth from UPSC preparation is a massive advantage. GS Paper 2 (Governance, IR) and Essay writing skills directly apply. Overlap Score: 85%',
  3, 'Moderate',
  '[{"title": "Introduction to Journalism", "provider": "Coursera (Northwestern)", "url": "https://www.coursera.org/learn/journalism", "free": false}, {"title": "Fact-Checking in the Digital Age", "provider": "edX (Duke)", "url": "https://www.edx.org", "free": true}]'::jsonb,
  ARRAY['PG Diploma in Journalism (IIMC)', 'Digital Media Certificate (Asian College of Journalism)'],
  ARRAY['Write and record a 2-minute news bulletin on a current topic', 'Produce a 10-minute YouTube news show episode', 'Publish 3 fact-check articles on any platform'],
  '[{"week": 1, "focus": "Media immersion", "tasks": ["Shadow a news show for 1 week", "Write 5 explainer briefs on current policy issues", "Read Nieman Lab for journalism insights"]}, {"week": 2, "focus": "Script craft", "tasks": ["Write scripts for 3 TV news segments (2 mins each)", "Study how NDTV/Rajya Sabha TV structure panels", "Learn basic video editing on CapCut or DaVinci Resolve"]}, {"week": 3, "focus": "Network building", "tasks": ["Apply for internship at The Wire, NDTV, News18", "Connect with bureau chiefs on LinkedIn", "Submit a story pitch to any digital news outlet"]}, {"week": 4, "focus": "Placement", "tasks": ["Build a clips portfolio with 5 published pieces", "Apply to news researcher/desk writer roles", "Consider PG Diploma in Broadcast Journalism (IIMC, AJK MCRC)"]}]'::jsonb,
  '₹50,000–₹1,50,000 (PG Diploma if pursued)',
  'Apply to NDTV, News18, India Today, Rajya Sabha TV directly. Send writing samples to editors on LinkedIn.',
  '[{"title": "How Indian TV News is Made", "channel": "The Newsroom India", "url": "https://youtube.com"}, {"title": "Journalism Career Guide India", "channel": "Media Careers", "url": "https://youtube.com"}]'::jsonb,
  '[{"title": "The Scroll Podcast", "platform": "Spotify", "url": "https://spotify.com"}]'::jsonb,
  '[{"name": "Indian Journalists Association", "url": "https://linkedin.com"}, {"name": "Digital Journalism India", "url": "https://linkedin.com"}]'::jsonb,
  ARRAY['Press Club of India', 'Indian Journalists Union (IJU)'],
  TRUE
),

-- 7. Documentary Filmmaker
(
  'Media, Journalism & Content',
  'Documentary Filmmaker',
  'documentary-filmmaker',
  'Tell the stories that matter — using the power of film to document India and the world.',
  'Documentary filmmaking is a powerful intersection of journalism, storytelling, and advocacy. Ex-UPSC aspirants often have deeply researched perspectives on social issues, history, governance failures, and policy — making them compelling documentary storytellers. Streaming platforms have created massive demand.',
  '₹5 LPA', '₹15 LPA', '₹50 LPA',
  ARRAY['Creative freedom', 'Travel', 'Festival recognition', 'Social impact', 'OTT opportunities'],
  'Create films that shift public opinion on important issues — from tribal rights to climate change to electoral reform.',
  'Work with OTT platforms, NGOs, international media organizations, and attend film festivals globally.',
  'No fixed requirement; strong research background is a major advantage',
  ARRAY['Storytelling', 'Scriptwriting', 'Video editing', 'Field research', 'Interviewing', 'Visual composition', 'Grant writing'],
  'UPSC research skills, GS knowledge of India''s social issues, and Essay writing craft all transfer directly to documentary making. Overlap Score: 65%',
  4, 'High',
  '[{"title": "Filmmaking Fundamentals", "provider": "MasterClass (Ron Howard)", "url": "https://www.masterclass.com/classes/ron-howard-teaches-directing", "free": false}, {"title": "DaVinci Resolve Complete Course", "provider": "YouTube (Darren Mostyn)", "url": "https://youtube.com", "free": true}]'::jsonb,
  ARRAY['FTII Short Course in Documentary', 'PSBT Grant Recipient', 'IDFA Academy Fellowship'],
  ARRAY['Direct a 10-minute documentary on a social issue in your city', 'Write a full documentary treatment and pitch deck', 'Submit one documentary to a film festival'],
  '[{"week": 1, "focus": "Craft study", "tasks": ["Watch 10 acclaimed Indian documentaries (Writing With Fire, An Insignificant Man)", "Study three-act structure in non-fiction storytelling", "Read ''Documentary Storytelling'' by Sheila Curran Bernard"]}, {"week": 2, "focus": "Equipment & editing", "tasks": ["Learn basic filming on your smartphone", "Complete a free DaVinci Resolve editing course", "Shoot a 3-minute mini-doc about your locality"]}, {"week": 3, "focus": "First project", "tasks": ["Choose a subject you researched for UPSC", "Script a 10-minute documentary treatment", "Apply for a doc film workshop (SRFTI, FTII short courses)"]}, {"week": 4, "focus": "Distribution", "tasks": ["Submit mini-doc to IDFA Doc Lab or MIFF open submissions", "Upload to YouTube and Vimeo", "Apply to PSBT grant program"]}]'::jsonb,
  '₹10,000–₹1,00,000 (equipment + FTII courses)',
  'Apply to PSBT, NFDC grants. Approach Netflix India and Disney+ Hotstar open submissions. Start on YouTube.',
  '[{"title": "How to Make a Documentary Film", "channel": "Filmmaker IQ", "url": "https://youtube.com/filmmakeriq"}, {"title": "India Documentary Scene", "channel": "Film Companion", "url": "https://youtube.com/filmcompanion"}]'::jsonb,
  '[{"title": "The Documentary Podcast", "platform": "Spotify", "url": "https://spotify.com"}]'::jsonb,
  '[{"name": "Documentary Filmmakers India", "url": "https://facebook.com"}, {"name": "FTII Alumni Network", "url": "https://linkedin.com"}]'::jsonb,
  ARRAY['FTII (Film and Television Institute of India)', 'PSBT (Public Service Broadcasting Trust)', 'NFDC India'],
  TRUE
),

-- 8. Public Sector Consultant
(
  'Management Consulting & Strategy',
  'Public Sector Consultant',
  'public-sector-consultant',
  'Use your governance expertise to advise government bodies as an external consultant.',
  'Public sector consulting sits at the intersection of policy, governance, and management. Firms like BCG, Deloitte, PwC, and EY have large government advisory practices. UPSC aspirants bring an edge no MBA can replicate: deep understanding of how government actually works, from Cabinet committees to district administration.',
  '₹12 LPA', '₹25 LPA', '₹60 LPA',
  ARRAY['High-impact projects', 'Exposure to senior government officials', 'Travel across India', 'Strong alumni networks'],
  'Drive large-scale government transformation — from digitizing services to redesigning welfare delivery.',
  'Present to Secretaries, Ministers, and State Chief Ministers. Work on projects that affect crores of citizens.',
  'Graduate; MBA/MPP from top institution preferred but not mandatory',
  ARRAY['Policy analysis', 'Stakeholder management', 'Presentation skills', 'Data analysis', 'Report writing', 'Project management', 'Excel/PowerPoint'],
  'Deep overlap with entire UPSC GS syllabus. Public Administration optional is directly applicable. Overlap Score: 90%',
  3, 'High',
  '[{"title": "Consulting Case Interview Prep", "provider": "Victor Cheng (free)", "url": "https://www.caseinterview.com", "free": true}, {"title": "McKinsey Problem Solving", "provider": "Coursera (McKinsey)", "url": "https://www.coursera.org/learn/mckinsey-problem-solving", "free": false}]'::jsonb,
  ARRAY['MBA from IIM/ISB (strong advantage)', 'PMP Certification', 'PRINCE2 Foundation'],
  ARRAY['Write a consulting proposal for a Smart City mission component', 'Build an Excel model for a government scheme budget analysis', 'Create a 20-slide transformation strategy for a state ministry'],
  '[{"week": 1, "focus": "Consulting toolkit", "tasks": ["Learn MECE thinking from Victor Cheng (free YouTube)", "Download and study a BCG or McKinsey public sector report", "Practice building a PowerPoint pyramid-principle presentation"]}, {"week": 2, "focus": "Domain specialization", "tasks": ["Pick a sector: smart cities, health, education, defence, agriculture", "Write a 1000-word policy brief on a current government initiative", "Read NITI Aayog reports and dissect their structure"]}, {"week": 3, "focus": "Applications", "tasks": ["Apply to EY, Deloitte, PwC, KPMG government advisory roles", "Target Primus Partners, i-government, CRISIL GR India", "Prepare case interviews with public sector scenarios"]}, {"week": 4, "focus": "Prep for interviews", "tasks": ["Practice 10 consulting case studies", "Prepare your UPSC-to-consulting story", "Get an MBA referral if possible"]}]'::jsonb,
  '₹0–₹5,00,000 (MBA optional but helpful)',
  'Apply via IIMJobs, LinkedIn. Target McKinsey, BCG, EY, Deloitte, Primus Partners, i-government.',
  '[{"title": "How to Get into Public Sector Consulting", "channel": "Management Consulted", "url": "https://youtube.com/managementconsulted"}, {"title": "India Public Policy Consulting", "channel": "Policy Circle", "url": "https://youtube.com"}]'::jsonb,
  '[{"title": "The Strategy Digest", "platform": "Spotify", "url": "https://spotify.com"}]'::jsonb,
  '[{"name": "Consulting Professionals India", "url": "https://linkedin.com"}, {"name": "Public Policy India Network", "url": "https://linkedin.com"}]'::jsonb,
  ARRAY['MCA (Management Consultancies Association)', 'CII Government Affairs'],
  TRUE
),

-- 9. Financial Journalist / Analyst
(
  'Banking, Finance & Economics',
  'Financial Journalist / Analyst',
  'financial-journalist-analyst',
  'Explain markets, money, and policy to India — as a writer or analyst.',
  'Financial journalism blends economics knowledge with writing and is booming with India''s growing investor class. UPSC aspirants with economics optional have a strong foundation in macro, fiscal policy, monetary policy, and public finance — exactly what financial media and research firms need.',
  '₹8 LPA', '₹18 LPA', '₹45 LPA',
  ARRAY['Byline recognition', 'Press passes to budget events', 'Market access', 'Intellectual stimulation'],
  'Inform India''s growing investor class and hold corporate and government financial decisions to account.',
  'Interact with CXOs, economists, RBI officials, and market participants. Attend Union Budget briefings.',
  'Graduate in Economics/Commerce; CFA or MA Economics is a strong plus',
  ARRAY['Macroeconomics', 'Financial statement reading', 'Data storytelling', 'Writing clarity', 'Source building', 'Excel', 'Bloomberg/CMIE basics'],
  'Economics optional maps directly. GS Paper 3 (Economy, Budget, RBI policy) is highly relevant. Overlap Score: 80%',
  3, 'High',
  '[{"title": "Bloomberg Market Concepts (BMC)", "provider": "Bloomberg", "url": "https://portal.bloombergforeducation.com/courses/bloomberg-market-concepts", "free": true}, {"title": "Financial Reporting and Analysis", "provider": "Coursera (Wharton)", "url": "https://www.coursera.org/learn/financial-reporting", "free": false}]'::jsonb,
  ARRAY['CFA Level 1', 'Bloomberg Market Concepts Certificate', 'NISM Equity Research Certification'],
  ARRAY['Write an explainer series on 5 economic indicators for general audiences', 'Build a financial model for a listed public sector company', 'Publish 5 financial analysis pieces on Substack or Medium'],
  '[{"week": 1, "focus": "Beat immersion", "tasks": ["Read Mint, Business Standard, and Livemint for 1 week", "Summarize 3 RBI policy documents in plain language", "Study Bloomberg Quint explainer structure"]}, {"week": 2, "focus": "Writing", "tasks": ["Write 3 original financial explainers (1000 words each)", "Publish on Medium or Substack", "Read ''The Economist Style Guide'' for financial writing craft"]}, {"week": 3, "focus": "Skills", "tasks": ["Learn basic Excel for financial modeling", "Get Bloomberg Market Concepts Certificate (free)", "Study India''s Union Budget structure and key ratios"]}, {"week": 4, "focus": "Apply", "tasks": ["Send writing samples to Mint, Business Standard editors", "Apply to CARE Ratings, CRISIL, ICRA for research associate roles", "Pitch a story idea to one digital outlet"]}]'::jsonb,
  '₹0–₹30,000 (CFA prep or Bloomberg certificate)',
  'Send writing samples directly to editors at Mint, Business Standard, MoneyControl. Apply to CRISIL, CARE for research roles.',
  '[{"title": "How to Become a Financial Journalist", "channel": "Journalism Careers India", "url": "https://youtube.com"}, {"title": "Indian Economy Explained", "channel": "Dhruv Rathee Economics", "url": "https://youtube.com"}]'::jsonb,
  '[{"title": "The Business Standard Podcast", "platform": "Spotify", "url": "https://spotify.com"}]'::jsonb,
  '[{"name": "Financial Journalists India", "url": "https://linkedin.com"}, {"name": "SEBI Research Analysts Network", "url": "https://linkedin.com"}]'::jsonb,
  ARRAY['Press Club of India', 'CFA Institute India Chapter'],
  TRUE
),

-- 10. Financial Advisor / Planner
(
  'Banking, Finance & Economics',
  'Financial Advisor / Planner',
  'financial-advisor-planner',
  'Help India''s growing middle class navigate wealth, tax, and retirement planning.',
  'India has an enormous advice gap — millions of people need financial planning guidance. UPSC aspirants with economics or commerce backgrounds can pivot to become SEBI-registered investment advisors (RIAs) or CFPs. The profession combines analytical rigor with empathetic client communication.',
  '₹7 LPA', '₹18 LPA', '₹50 LPA',
  ARRAY['Build your own practice', 'Recurring client income', 'Flexible work hours', 'High growth sector'],
  'Help millions of Indians make better financial decisions — closing India''s massive financial literacy and advice gap.',
  'Work with HNI clients, corporates, and retail investors. Engage with SEBI, AMFI, and tax authorities.',
  'Graduate; CFP or SEBI-RIA certification required',
  ARRAY['Personal finance', 'Investment analysis', 'Tax planning', 'Communication', 'Client relationship management', 'Risk profiling'],
  'Economics optional provides macro foundation. GS Paper 3 (Economy, Budget, Banking) is highly relevant. Overlap Score: 65%',
  3, 'High',
  '[{"title": "CFP Certification Program", "provider": "FPSB India", "url": "https://www.fpsbindia.org", "free": false}, {"title": "NISM Mutual Fund Distributor", "provider": "NISM", "url": "https://www.nism.ac.in", "free": false}]'::jsonb,
  ARRAY['CFP (Certified Financial Planner) — FPSB India', 'SEBI-RIA Registration', 'NISM Series V-A, X-A, X-B'],
  ARRAY['Create a complete financial plan for a hypothetical client (30-year-old IT professional)', 'Build a retirement calculator in Excel', 'Write a 10-part personal finance guide for first-time earners'],
  '[{"week": 1, "focus": "Finance foundation", "tasks": ["Read ''Let''s Talk Money'' by Monika Halan", "Complete NISM Series V-A syllabus overview", "Study income tax basics: 80C, LTCG, STCG, NPS"]}, {"week": 2, "focus": "Certification prep", "tasks": ["Register for NISM Series V-A exam (Rs 1500 fee)", "Study CFP certification requirements (FPSB India)", "Build a sample financial plan for a hypothetical 30-year-old"]}, {"week": 3, "focus": "Market immersion", "tasks": ["Open a demat account and invest a small amount hands-on", "Study 3 sample financial plans online", "Follow SEBI circulars for latest RIA regulations"]}, {"week": 4, "focus": "Career path", "tasks": ["Apply to Scripbox, Fisdom, ICICI Direct, Motilal Oswal", "Register for SEBI-RIA if planning independent practice", "Start a personal finance blog as thought leadership"]}]'::jsonb,
  '₹5,000–₹50,000 (CFP exam + SEBI registration)',
  'Apply via LinkedIn Jobs, Naukri to Scripbox, Fisdom, Zerodha, HDFC Securities. Or set up SEBI-RIA independent practice.',
  '[{"title": "Financial Planning Career India", "channel": "Freefincal", "url": "https://youtube.com/freefincal"}, {"title": "CFP Career Path India", "channel": "FPSB India", "url": "https://youtube.com"}]'::jsonb,
  '[{"title": "Paisa Vaisa", "platform": "Spotify", "url": "https://open.spotify.com/show/paisavaisa"}]'::jsonb,
  '[{"name": "SEBI Registered Investment Advisors", "url": "https://linkedin.com"}, {"name": "CFP India Network", "url": "https://linkedin.com"}]'::jsonb,
  ARRAY['FPSB India (Financial Planning Standards Board)', 'AMFI (Association of Mutual Funds in India)'],
  TRUE
),

-- 11. International Trade Analyst
(
  'International Relations & Diplomacy',
  'International Trade Analyst',
  'international-trade-analyst',
  'Shape India''s trade policy or work for corporations navigating global markets.',
  'India''s trade policy landscape is growing complex with FTAs, WTO negotiations, and geopolitical realignments. UPSC aspirants with international relations or economics optional understand these dynamics deeply. Trade analysts work in policy think tanks, export promotion bodies, or multinational trading firms.',
  '₹10 LPA', '₹20 LPA', '₹45 LPA',
  ARRAY['International exposure', 'Policy conferences and delegations', 'Possibility of postings abroad', 'Intellectual prestige'],
  'Shape India''s trade relationships that affect millions of exporters, farmers, and manufacturing workers.',
  'Engage with WTO, bilateral trade ministers, exporters, industry chambers like FICCI and CII.',
  'Graduate in Economics/International Relations/Law; LL.M in International Trade or MA Economics preferred',
  ARRAY['Trade law', 'WTO agreements', 'Tariff analysis', 'EXIM policy', 'Data analysis', 'Report writing', 'Foreign policy'],
  'International Relations optional maps directly. Economics optional for trade economics. GS Paper 2 (IR) and GS Paper 3 (Economy) are both highly relevant. Overlap Score: 85%',
  3, 'High',
  '[{"title": "International Trade Law", "provider": "Coursera (Yonsei University)", "url": "https://www.coursera.org/learn/international-trade-law", "free": false}, {"title": "Trade in Goods and Services (WTO)", "provider": "WTO e-Learning", "url": "https://etraining.wto.org", "free": true}]'::jsonb,
  ARRAY['WTO e-Learning Certificate', 'DGFT EXIM Certification', 'MA International Economics (JNU/BHU)'],
  ARRAY['Analyze a recent India FTA and write a sector-wise impact assessment', 'Build an interactive trade dashboard using DGCI&S data', 'Write a policy brief on India''s China+1 manufacturing opportunity'],
  '[{"week": 1, "focus": "Foundation", "tasks": ["Study India''s Foreign Trade Policy 2023 (DGFT website)", "Read WTO website primer on GATT and trade in goods", "Analyze India''s top 10 trading partners using DGCI&S data"]}, {"week": 2, "focus": "Technical skills", "tasks": ["Learn to use UN Comtrade database", "Study an FTA India recently signed (India-UAE CEPA)", "Write a 1000-word trade impact brief on one sector"]}, {"week": 3, "focus": "Target organizations", "tasks": ["Research FICCI, CII, GTRI, ORF, CUTS International, Exim Bank", "Apply for research fellowships at trade policy think tanks", "Connect with trade analysts at FICCI and ORF on LinkedIn"]}, {"week": 4, "focus": "Applications", "tasks": ["Apply to Exim Bank India, ECGC, FICCI/CII trade divisions", "Apply to multinational trading companies (Tata International, MMTC)", "Submit a trade research abstract to ORF"]}]'::jsonb,
  '₹0–₹20,000 (certifications)',
  'Apply via IIMJobs and LinkedIn. Target Exim Bank India, FICCI, CII, CUTS International, Tata International, MMTC.',
  '[{"title": "India''s Trade Policy Explained", "channel": "GTRI India", "url": "https://youtube.com"}, {"title": "WTO Basics", "channel": "WTO Official", "url": "https://youtube.com/WTO"}]'::jsonb,
  '[{"title": "Trade Winds Podcast", "platform": "Spotify", "url": "https://spotify.com"}]'::jsonb,
  '[{"name": "International Trade Professionals India", "url": "https://linkedin.com"}, {"name": "WTO Young Professionals Network", "url": "https://linkedin.com"}]'::jsonb,
  ARRAY['CUTS International', 'FICCI Trade Committee', 'WTO India'],
  TRUE
),

-- 12. GovTech / CivicTech Professional
(
  'Data, Analytics & Tech-Adjacent',
  'GovTech / CivicTech Professional',
  'govtech-civictech',
  'Build the digital infrastructure that makes government work better for citizens.',
  'GovTech is one of India''s most exciting growth areas — from digital public infrastructure (UPI, ONDC, DigiYatra) to state-level e-governance. UPSC aspirants understand government processes deeply, and combined with even moderate tech skills, they''re uniquely positioned to bridge the gap between government and technology.',
  '₹10 LPA', '₹22 LPA', '₹50 LPA',
  ARRAY['High-impact work', 'Access to senior government officials', 'India-scale problems', 'Growing ecosystem'],
  'Build the digital India that serves a billion citizens — from DigiLocker to ONDC to Aarogya Setu.',
  'Work with NITI Aayog, MeitY, state governments, and leading GovTech startups. Attend Digital India conferences.',
  'Graduate; engineering or public policy background preferred',
  ARRAY['Government process knowledge', 'Product thinking', 'Stakeholder management', 'Digital policy', 'Data literacy', 'SQL basics', 'UX basics'],
  'UPSC GS knowledge of government functioning, schemes, and administration is the core advantage here. Overlap Score: 90%',
  3, 'High',
  '[{"title": "Digital Government and Public Innovation", "provider": "edX (MIT)", "url": "https://www.edx.org/course/digital-government", "free": false}, {"title": "Product Management Fundamentals", "provider": "Google (free)", "url": "https://grow.google/intl/en_in/courses-and-tools/", "free": true}]'::jsonb,
  ARRAY['Google Project Management Certificate', 'PMP', 'NASSCOM FutureSkills Digital Leadership'],
  ARRAY['Design a citizen-facing app redesign for a government service (e.g., ration card portal)', 'Write a policy note on India''s ONDC vs Amazon/Flipkart', 'Map the end-to-end user journey for a government scheme application process'],
  '[{"week": 1, "focus": "India''s digital stack", "tasks": ["Study India Stack: Aadhaar, UPI, DigiLocker, ONDC, ABDM", "Read MeitY''s National e-Governance Plan", "Follow iSPIRT, NASSCOM, and EkStep Foundation"]}, {"week": 2, "focus": "Tech basics", "tasks": ["Learn SQL basics (free on Mode Analytics or SQLZoo)", "Take Google''s free PM Certification course", "Understand REST APIs conceptually"]}, {"week": 3, "focus": "Network", "tasks": ["Apply to iGOT Karmayogi, EkStep, or Samagra Governance", "Connect with IDInsight, J-PAL, and Dalberg India", "Attend GovTech Summit events"]}, {"week": 4, "focus": "Apply", "tasks": ["Apply to MeitY Startup Hub fellowship", "Target Samagra Governance, Agami, NITI Aayog consultancies", "Build a government service redesign case study"]}]'::jsonb,
  '₹0–₹20,000 (certifications)',
  'Apply via LinkedIn. Target Samagra Governance, EkStep Foundation, iSPIRT, IDInsight India, MeitY Startup Hub.',
  '[{"title": "India Stack Explained", "channel": "iSPIRT Foundation", "url": "https://youtube.com/ispirt"}, {"title": "GovTech India", "channel": "Samagra Governance", "url": "https://youtube.com"}]'::jsonb,
  '[{"title": "The Agami Podcast", "platform": "Spotify", "url": "https://spotify.com"}]'::jsonb,
  '[{"name": "GovTech India", "url": "https://linkedin.com"}, {"name": "iSPIRT Volunteers Network", "url": "https://linkedin.com"}]'::jsonb,
  ARRAY['iSPIRT Foundation', 'NASSCOM', 'MeitY Startup Hub'],
  TRUE
),

-- 13. Fundraising & Grant Writer
(
  'Social Sector & Non-Profit',
  'Fundraising & Grant Writer',
  'fundraising-grant-writer',
  'Help nonprofits and NGOs secure the resources to change India.',
  'Fundraising and grant writing is a high-demand, underserved profession in India''s growing social sector. UPSC aspirants excel here — they understand government schemes, policy priorities, and can write compelling proposals. With India''s CSR mandate creating billions in annual grants, skilled fundraisers are sought-after.',
  '₹7 LPA', '₹15 LPA', '₹35 LPA',
  ARRAY['Meaningful work', 'Exposure to India''s top foundations', 'Flexible hours in many NGOs', 'Network with change-makers'],
  'Directly enable organizations solving India''s hardest problems — from rural education to disability inclusion — by securing the funding they need.',
  'Work with Tata Trusts, Azim Premji Foundation, HDFC Parivartan, and international foundations like BMGF.',
  'Graduate in any field; social work/development studies/MBA preferred',
  ARRAY['Proposal writing', 'Research', 'Relationship management', 'Data reporting', 'Government scheme knowledge', 'Storytelling'],
  'Understanding of government schemes (GS Paper 2 & 3), social issues (GS Paper 1), and strong writing skills (Mains Essay) are all highly transferable. Overlap Score: 75%',
  2, 'High',
  '[{"title": "Grant Writing Essentials", "provider": "Coursera (UW)", "url": "https://www.coursera.org/learn/grant-writing", "free": false}, {"title": "Social Impact Measurement", "provider": "edX (MIT)", "url": "https://www.edx.org", "free": false}]'::jsonb,
  ARRAY['CFRE (Certified Fund Raising Executive)', 'CSR Management Certificate (ISB/XLRI)', 'PGD in Development Studies'],
  ARRAY['Write a full grant proposal for a hypothetical rural sanitation project', 'Create a CSR pitch deck for a corporate health program', 'Build a donor impact report template for an education NGO'],
  '[{"week": 1, "focus": "Grant ecosystem", "tasks": ["Study major Indian CSR funders: Tata Trusts, Azim Premji Foundation", "Read 3 successful grant proposals (search online for samples)", "Understand FCRA compliance and CSR Schedule VII requirements"]}, {"week": 2, "focus": "Writing practice", "tasks": ["Write a mock grant proposal for a hypothetical NGO (education sector)", "Study the logical framework (logframe) format", "Study how Pratham and Akshara Foundation frame their impact"]}, {"week": 3, "focus": "Network", "tasks": ["Join GuideStar India / Credibility Alliance", "Connect with development sector HR on LinkedIn", "Attend a CFP India or Give India webinar"]}, {"week": 4, "focus": "Apply", "tasks": ["Apply to Tata Trusts, Dasra, CIFF India for grants associate roles", "Build a portfolio of 3 sample grant proposals", "Register on Devex for international development roles"]}]'::jsonb,
  '₹0–₹30,000 (certifications optional)',
  'Apply via Devex, LinkedIn, iVolunteer.in. Target Tata Trusts, Dasra, Azim Premji Foundation, Give India.',
  '[{"title": "Fundraising for Nonprofits India", "channel": "iVolunteer India", "url": "https://youtube.com"}]'::jsonb,
  '[{"title": "The Social Entrepreneur India", "platform": "Spotify", "url": "https://spotify.com"}]'::jsonb,
  '[{"name": "Development Sector India", "url": "https://linkedin.com"}, {"name": "NGO India Network", "url": "https://facebook.com"}]'::jsonb,
  ARRAY['CFRE International', 'GuideStar India', 'Credibility Alliance India'],
  TRUE
),

-- 14. Public Relations Consultant
(
  'Communication, PR & Corporate Affairs',
  'Public Relations Consultant',
  'public-relations-consultant',
  'Shape narratives for brands, politicians, and institutions using your communication skills.',
  'PR consultants manage reputation, craft messaging, and navigate media — skills that UPSC aspirants have honed through years of essay writing and current affairs mastery. Government affairs PR is especially in demand as companies seek to navigate India''s complex regulatory and political landscape.',
  '₹9 LPA', '₹20 LPA', '₹45 LPA',
  ARRAY['Fast-paced exciting work', 'Media access', 'Build powerful networks', 'Variety of sectors and clients'],
  'Shape public perception of organizations and causes that matter — from government schemes to corporate responsibility.',
  'Work with CEOs, ministers, brand heads, and journalists. Represent clients at high-profile press events.',
  'Graduate in any field; Mass Communication or Journalism PG is helpful',
  ARRAY['Writing', 'Media relations', 'Crisis communication', 'Messaging strategy', 'Social media', 'Stakeholder mapping', 'Government affairs'],
  'Essay writing, current affairs mastery, and governance knowledge from UPSC preparation are all directly applicable. Overlap Score: 75%',
  2, 'Stable',
  '[{"title": "Public Relations and Media", "provider": "Coursera (PRSA)", "url": "https://www.coursera.org/learn/public-relations-media", "free": false}, {"title": "Crisis Communication", "provider": "LinkedIn Learning", "url": "https://www.linkedin.com/learning", "free": false}]'::jsonb,
  ARRAY['APR (Accreditation in Public Relations) — PRSA', 'PG Diploma in PR (IIMC / Symbiosis)', 'Google Digital Marketing Certificate'],
  ARRAY['Write a full crisis communication plan for a hypothetical company data breach', 'Create a government affairs strategy for a fintech seeking RBI approval', 'Build a media list and write 3 tailored journalist pitches'],
  '[{"week": 1, "focus": "PR fundamentals", "tasks": ["Read ''Trust Me, I''m Lying'' by Ryan Holiday", "Study 5 press releases from Fortune 500 India companies", "Follow PRCAI (PR Council of India) for industry updates"]}, {"week": 2, "focus": "Writing", "tasks": ["Write 3 press releases on current events from a company perspective", "Write a crisis communication response for a hypothetical scandal", "Study Adfactors PR and Edelman India case studies"]}, {"week": 3, "focus": "Government affairs angle", "tasks": ["Research Government Affairs PR in pharma, infrastructure, and tech sectors", "Write a government affairs strategy for a hypothetical company entering India", "Connect with Corporate Affairs heads on LinkedIn"]}, {"week": 4, "focus": "Apply", "tasks": ["Apply to Adfactors PR, MSLGROUP, Weber Shandwick, Edelman India", "Apply to in-house corporate communications roles at FMCG/pharma companies", "Publish 3 articles on LinkedIn about communication strategy"]}]'::jsonb,
  '₹0–₹50,000 (PG Diploma optional)',
  'Apply via LinkedIn Jobs, Campaign India job board. Target Adfactors PR, MSLGROUP, Weber Shandwick, Edelman India.',
  '[{"title": "PR Career in India", "channel": "PRCAI", "url": "https://youtube.com"}, {"title": "Crisis PR Masterclass", "channel": "PR Daily", "url": "https://youtube.com/prdaily"}]'::jsonb,
  '[{"title": "Reputation Matters", "platform": "Spotify", "url": "https://spotify.com"}]'::jsonb,
  '[{"name": "PR Professionals India", "url": "https://linkedin.com"}, {"name": "PRCAI India Members Network", "url": "https://linkedin.com"}]'::jsonb,
  ARRAY['PRCAI (Public Relations Consultants Association of India)', 'IABC India'],
  TRUE
),

-- 15. EIA Analyst
(
  'Environment & Sustainability',
  'Environmental Impact Assessment (EIA) Analyst',
  'eia-analyst',
  'Assess the environmental cost of development — and be India''s conscience.',
  'With India''s infrastructure boom, Environmental Impact Assessment is both legally mandated and chronically understaffed with quality analysts. UPSC aspirants with geography or environment optional understand EIA concepts deeply from exam preparation.',
  '₹8 LPA', '₹18 LPA', '₹40 LPA',
  ARRAY['Field travel across India', 'Direct environmental impact', 'Government interaction', 'Growing sector'],
  'Protect India''s ecosystems and communities by ensuring development projects account for their environmental costs.',
  'Interact with MoEFCC, SEIAA, NGT, and local communities. Represent projects at public hearings.',
  'Graduate in Environmental Science/Geography/Civil Engineering; M.Sc. Environment preferred',
  ARRAY['Environmental law', 'GIS basics', 'Report writing', 'Ecological assessment', 'Regulatory compliance', 'Data collection', 'Stakeholder consultation'],
  'Geography optional (environment, ecology chapters), GS Paper 3 (Environment), and Public Administration optional are all highly relevant. Overlap Score: 75%',
  3, 'High',
  '[{"title": "Environmental Impact Assessment", "provider": "NPTEL (IIT)", "url": "https://nptel.ac.in/courses/105/105/105105034", "free": true}, {"title": "GIS and Remote Sensing for EIA", "provider": "ESRI Training", "url": "https://www.esri.com/training", "free": false}]'::jsonb,
  ARRAY['IGBC Green AP / Green Fellow', 'TERI EIA Professional Certificate', 'LEAD India Environmental Leadership'],
  ARRAY['Write a complete EIA executive summary for a hypothetical industrial project', 'Create a GIS map of land use change for a peri-urban area using QGIS', 'Analyze a publicly available EIA report on MoEFCC''s Parivesh portal'],
  '[{"week": 1, "focus": "Regulatory framework", "tasks": ["Read MoEFCC EIA Notification 2006 and amendments", "Study EIA categories A and B from the Schedule", "Download and analyze 2 public EIA reports from MoEFCC website"]}, {"week": 2, "focus": "Technical skills", "tasks": ["Learn QGIS basics (free GIS software) from YouTube", "Study baseline data types: air quality, water quality, ecology, socioeconomics", "Write a mock EIA executive summary for a hypothetical highway project"]}, {"week": 3, "focus": "Certifications", "tasks": ["Enroll in TERI EIA training or IGBC Green AP exam", "Study ISO 14001 Environmental Management System basics", "Connect with environmental consultants at ERM, AECOM"]}, {"week": 4, "focus": "Apply", "tasks": ["Apply to ERM India, AECOM, Environ Consulting, IL&FS Environment", "Apply to MoEFCC expert appraisal committees (after 2+ years experience)", "Build an EIA sample report portfolio"]}]'::jsonb,
  '₹10,000–₹50,000 (TERI/IGBC certifications)',
  'Apply via LinkedIn Jobs, Naukri. Target ERM India, AECOM India, Environ Consulting, IL&FS Environment, Feedback Infrastructure.',
  '[{"title": "EIA Process India Explained", "channel": "Environment India", "url": "https://youtube.com"}, {"title": "QGIS for Beginners (Hindi)", "channel": "GIS Tutorial India", "url": "https://youtube.com"}]'::jsonb,
  '[{"title": "The Green Corridor", "platform": "Spotify", "url": "https://spotify.com"}]'::jsonb,
  '[{"name": "EIA Professionals India", "url": "https://linkedin.com"}, {"name": "IGBC Professionals Network", "url": "https://linkedin.com"}]'::jsonb,
  ARRAY['IGBC (Indian Green Building Council)', 'TERI India', 'MoEFCC Expert Network'],
  TRUE
),

-- 16. Regional Language Translator
(
  'Creative & Unconventional',
  'Regional Language Translator / Localizer',
  'regional-language-translator',
  'Bridge language divides — making content, policy, and media accessible across India.',
  'India''s digital and policy communications need quality translators who understand context, not just words. UPSC aspirants proficient in Hindi, regional languages, and English are perfectly positioned. From OTT subtitle localization to government document translation and international organization work, opportunities are growing rapidly.',
  '₹6 LPA', '₹14 LPA', '₹30 LPA',
  ARRAY['Remote-friendly', 'Build a freelance income', 'Work with global organizations', 'Flexible hours'],
  'Enable millions of Indians to access content, legal information, and government services in their native language.',
  'Work with Netflix, UN India, WHO, government bodies, and major OTT platforms.',
  'Graduate; language degree or translator certification preferred; native proficiency in 2+ languages required',
  ARRAY['Native-level proficiency in 2+ languages', 'Domain terminology', 'CAT tools (SDL Trados, MemoQ)', 'Attention to detail', 'Cultural context', 'Legal or technical writing'],
  'Optional language subjects (Hindi, Urdu, regional language literatures) map directly. Strong writing skills from Mains preparation. Overlap Score: 60%',
  2, 'High',
  '[{"title": "Introduction to Translation Studies", "provider": "Coursera (Leiden)", "url": "https://www.coursera.org/learn/translation", "free": false}, {"title": "SDL Trados Studio Training", "provider": "SDL Training", "url": "https://www.sdl.com/company/events/webinars", "free": true}]'::jsonb,
  ARRAY['ATA Certification (American Translators Association)', 'BCI Diploma in Translation (UK)', 'PGDT — PG Diploma in Translation (CIIL Mysore)'],
  ARRAY['Translate a 2000-word policy document into your regional language', 'Create a 5-episode subtitled video series of English content in Hindi/Tamil/Telugu', 'Build a bilingual glossary of 200 government/policy terms'],
  '[{"week": 1, "focus": "Market mapping", "tasks": ["Register on ProZ.com and Translators Café", "Identify your language pair(s) and specialization (legal, policy, media)", "Translate 3 government press releases from English to your regional language"]}, {"week": 2, "focus": "Tools", "tasks": ["Download and practice SDL Trados free trial or OmegaT (free)", "Study CAT (Computer-Assisted Translation) tool basics", "Take a free subtitling tutorial on YouTube (Amara/Aegisub)"]}, {"week": 3, "focus": "Clients", "tasks": ["Apply to Netflix/Amazon India localization vendors (EFG, Vista India, Prime Focus Technologies)", "Approach UN OCHA and WHO India for Hindi translation contracts", "Connect with the Translators Association of India (TAI)"]}, {"week": 4, "focus": "Revenue", "tasks": ["Set up profiles on Gengo and One Hour Translation", "Apply to Prasar Bharati and DD National for staff translator roles", "Aim to submit one paid translation project this week"]}]'::jsonb,
  '₹5,000–₹30,000 (software + certification)',
  'Register on ProZ.com, Translators Café, Gengo. Apply to EFG India, Prime Focus Technologies, Prasar Bharati, UN India.',
  '[{"title": "Translation Career India — How to Start", "channel": "Translator Training", "url": "https://youtube.com"}, {"title": "OTT Localization in India", "channel": "Media Localization Hub", "url": "https://youtube.com"}]'::jsonb,
  '[{"title": "The Translator''s Roadmap", "platform": "Spotify", "url": "https://spotify.com"}]'::jsonb,
  '[{"name": "Translators Association of India (TAI)", "url": "https://linkedin.com"}, {"name": "ProZ India Community", "url": "https://linkedin.com"}]'::jsonb,
  ARRAY['Translators Association of India (TAI)', 'CIIL (Central Institute of Indian Languages)'],
  TRUE
),

-- 17. CDS Officer
(
  'Armed Forces & Paramilitary',
  'CDS Officer (Combined Defence Services)',
  'cds-officer',
  'Serve the nation in uniform — through the UPSC Combined Defence Services exam.',
  'CDS is UPSC''s own exam for entry into the Indian Army, Navy, and Air Force as commissioned officers. For UPSC-CSE aspirants under 24 (or OTA under 25), this is a near-perfect pivot. The preparation overlaps significantly — GK, English, and mathematical reasoning — and the IMA/OTA path offers a prestigious career with excellent perks.',
  '₹8 LPA', '₹13 LPA', '₹20 LPA',
  ARRAY['Government housing', 'Full healthcare for family', 'Pension', 'Prestigious posting opportunities', 'Pre-commission training at IMA/OTA'],
  'Serve and protect India''s sovereignty. Lead soldiers in the world''s second-largest standing army.',
  'Lead platoons, work across India and internationally. Potential postings with UN peacekeeping missions.',
  'Graduate (any stream); age 19–24 for IMA/INA/AFA, 19–25 for OTA',
  ARRAY['Leadership', 'Physical fitness', 'General knowledge', 'Decision-making under pressure', 'Map reading', 'Team management'],
  'GS current affairs, history, polity, and geography preparation for UPSC directly supports CDS GK paper. Essay and English writing skills transfer directly. Overlap Score: 95%',
  3, 'Stable',
  '[{"title": "CDS Complete Preparation", "provider": "Unacademy Defence", "url": "https://unacademy.com/goal/cds", "free": false}, {"title": "SSB Interview Preparation", "provider": "SSBCrack", "url": "https://ssbcrack.com", "free": true}]'::jsonb,
  ARRAY['CDS (UPSC exam)', 'SSB Interview Clearance', 'Pre-Commission Training (IMA/OTA/INA/AFA)'],
  ARRAY['Write a 400-word essay on a current defence policy topic', 'Complete 5 full CDS GK and English previous year papers', 'Complete 30-day physical fitness baseline challenge (record progress)'],
  '[{"week": 1, "focus": "Eligibility check", "tasks": ["Verify age eligibility: IMA (< 24), OTA (< 25)", "Download CDS syllabus and previous year papers from UPSC website", "Compare CDS GK syllabus with your UPSC prep"]}, {"week": 2, "focus": "Written exam", "tasks": ["Start daily newspaper reading for current affairs", "Revise elementary mathematics (CDS has a dedicated maths paper)", "Practice English comprehension and grammar"]}, {"week": 3, "focus": "SSB preparation", "tasks": ["Study SSB process: OIR, PPDT, GD, personal interview", "Read ''How to Crack SSB Interview'' by Arihant Publications", "Start physical fitness training: running, push-ups, pull-ups"]}, {"week": 4, "focus": "Apply and practice", "tasks": ["Register on UPSC online portal for the next CDS cycle", "Take 2 full-length CDS mock tests", "Connect with NDA/CDS qualifiers on SSBCrack forum"]}]'::jsonb,
  '₹5,000–₹20,000 (test series and books)',
  'Register on UPSC official website (upsc.gov.in) for the next CDS notification. Physical fitness is key — start preparing immediately.',
  '[{"title": "CDS Preparation Guide", "channel": "SSBCrack", "url": "https://youtube.com/ssbcrack"}, {"title": "SSB Interview Tips", "channel": "Career Defence India", "url": "https://youtube.com"}]'::jsonb,
  '[{"title": "SSBCrack Podcast", "platform": "Spotify", "url": "https://spotify.com"}]'::jsonb,
  '[{"name": "SSB Interview Aspirants India", "url": "https://t.me"}, {"name": "CDS Prep Group", "url": "https://facebook.com"}]'::jsonb,
  ARRAY['Indian Army (joinindianarmy.nic.in)', 'Indian Navy', 'Indian Air Force'],
  TRUE
),

-- 18. Rehabilitation Counselor
(
  'Psychology & Counseling',
  'Rehabilitation Counselor',
  'rehabilitation-counselor',
  'Help people rebuild their lives after trauma, disability, or addiction.',
  'Rehabilitation counselors support individuals facing physical disabilities, mental health challenges, addiction recovery, or trauma. India has a massive shortage of trained counselors. For UPSC aspirants drawn to public service and human welfare, this is a deeply fulfilling path that directly serves vulnerable populations.',
  '₹6 LPA', '₹14 LPA', '₹28 LPA',
  ARRAY['Deeply meaningful work', 'Societal impact', 'Government job opportunities (MSJE)', 'Growing demand post-pandemic'],
  'Help India''s most vulnerable populations — persons with disabilities, addiction survivors, and trauma victims — rebuild their lives with dignity.',
  'Work with NIMHANS, AIIMS, government disability centers, and leading NGOs. Engage with Ministry of Social Justice & Empowerment.',
  'Graduate; Master''s in Psychology/Social Work/Rehabilitation required; RCI registration needed',
  ARRAY['Empathy', 'Active listening', 'Case management', 'Disability law (RPWD Act 2016)', 'Report writing', 'Psychological assessment basics', 'Crisis intervention'],
  'Understanding of social issues from GS Paper 1 and social justice policies from GS Paper 2 are relevant. Sociology optional is directly applicable. Overlap Score: 50%',
  4, 'High',
  '[{"title": "Introduction to Clinical Psychology", "provider": "Coursera (Yale)", "url": "https://www.coursera.org/learn/clinical-psychology", "free": false}, {"title": "Mental Health First Aid India", "provider": "iCall / TISS", "url": "https://icallhelpline.org", "free": true}]'::jsonb,
  ARRAY['RCI Registration (Rehabilitation Council of India)', 'M.Sc. in Clinical Psychology / MSW', 'Mental Health First Aid Certification'],
  ARRAY['Write a rehabilitation plan for a hypothetical client with acquired disability', 'Complete Mental Health First Aid certification and write a reflection', 'Design a community awareness program for disability rights in a district'],
  '[{"week": 1, "focus": "Foundation", "tasks": ["Read the Rights of Persons with Disabilities Act 2016", "Explore RCI (Rehabilitation Council of India) registration requirements", "Read ''Man''s Search for Meaning'' by Viktor Frankl"]}, {"week": 2, "focus": "Education path", "tasks": ["Research M.A. Psychology / MSW programs at Delhi University, TISS, Jamia", "Explore IGNOU MA Psychology (distance) for working professionals", "Attend a virtual seminar from iCall (TISS) or Vandrevala Foundation"]}, {"week": 3, "focus": "Volunteering", "tasks": ["Volunteer at iCall helpline or an addiction recovery center", "Take a free crisis counseling training from iCall or AASRA", "Connect with rehabilitation counselors at NIMHANS or AIIMS"]}, {"week": 4, "focus": "Career plan", "tasks": ["Apply to government rehabilitation centers under MSJE", "Apply to Vandrevala Foundation, iCall, Sangath for paid roles", "Register for RCI-approved training if you have a psychology background"]}]'::jsonb,
  '₹1,00,000–₹3,00,000 (MA Psychology or MSW program)',
  'Apply via LinkedIn Jobs, Naukri to Vandrevala Foundation, iCall TISS, Sangath, Asha for Education, Government DDRC Centers.',
  '[{"title": "Career in Counseling Psychology India", "channel": "Psychology India", "url": "https://youtube.com"}, {"title": "Disability Rights India", "channel": "NCPEDP", "url": "https://youtube.com"}]'::jsonb,
  '[{"title": "The Mind Space", "platform": "Spotify", "url": "https://spotify.com"}]'::jsonb,
  '[{"name": "Mental Health Professionals India", "url": "https://linkedin.com"}, {"name": "RCI India Network", "url": "https://linkedin.com"}]'::jsonb,
  ARRAY['RCI (Rehabilitation Council of India)', 'NIMHANS', 'Vandrevala Foundation'],
  TRUE
),

-- 19. Satirical Content Creator / Stand-up Comedian
(
  'Entrepreneurship & Freelancing',
  'Satirical Content Creator / Stand-up Comedian',
  'satirical-content-creator',
  'Make India laugh at itself — and build a career from political satire and social commentary.',
  'India''s stand-up comedy and political satire scene has exploded, and its best voices combine wit with deep knowledge of policy, history, and society — exactly what UPSC aspirants have. From Netflix specials to YouTube channels with millions of followers, the medium has become mainstream and commercially viable.',
  '₹3 LPA', '₹15 LPA', '₹80 LPA',
  ARRAY['Creative freedom', 'No fixed office hours', 'Grow a devoted fan base', 'Netflix/OTT specials possible'],
  'Use humor to hold power accountable and help India process its complex political reality — a form of public service in its own right.',
  'Perform at Canvas Laugh Club, The Comedy Store India, corporate events. Collaborate with Netflix, Amazon, OML Entertainment.',
  'No formal requirement; UPSC knowledge of politics, history, and society is a massive advantage',
  ARRAY['Writing', 'Public speaking', 'Timing', 'Cultural observation', 'Social media', 'Video editing', 'Resilience'],
  'Deep knowledge of Indian polity, history, society, and current affairs from UPSC preparation is the core competitive advantage. Overlap Score: 60%',
  5, 'High',
  '[{"title": "Stand-up Comedy Writing", "provider": "MasterClass (Steve Martin)", "url": "https://www.masterclass.com/classes/steve-martin-teaches-comedy", "free": false}, {"title": "YouTube Creator Academy", "provider": "YouTube (free)", "url": "https://creatoracademy.youtube.com", "free": true}]'::jsonb,
  ARRAY['No formal certifications — your audience size and specials ARE your credentials'],
  ARRAY['Write and perform a full 10-minute stand-up set on tape', 'Create a 10-episode satirical YouTube series on Indian politics', 'Pitch an original satirical show concept to an OTT platform'],
  '[{"week": 1, "focus": "Study the craft", "tasks": ["Watch every Kunal Kamra, Varun Grover, and Vir Das special", "Read ''Born Standing Up'' by Steve Martin", "Write a 5-minute set about your UPSC journey — find the humor"]}, {"week": 2, "focus": "First performance", "tasks": ["Find open mics in your city on Instagram (#openmicdelhi etc.)", "Sign up for your first open mic — 5 minutes only", "Record your set on phone and watch it back critically"]}, {"week": 3, "focus": "Content creation", "tasks": ["Start a YouTube Shorts / Instagram Reels series on political satire", "Post 3 satirical takes on current news events this week", "Study how Dhruv Rathee structures his YouTube scripts"]}, {"week": 4, "focus": "Community", "tasks": ["Join open mic community: Canvas Laugh Club, The Comedy Store India", "Connect with other comics on Instagram and collaborate", "Write and test 10 new jokes this week"]}]'::jsonb,
  '₹0–₹10,000 (basic recording equipment)',
  'Start at open mics in your city. Build a social media following. Approach Canvas Laugh Club, OML Entertainment for paid shows once you have material.',
  '[{"title": "Kunal Kamra: Honest Talk", "channel": "Kunal Kamra", "url": "https://youtube.com/kunalkamra"}, {"title": "How to Start Stand-up Comedy in India", "channel": "The Comedy Hub", "url": "https://youtube.com"}]'::jsonb,
  '[{"title": "The Comedy India Podcast", "platform": "Spotify", "url": "https://spotify.com"}]'::jsonb,
  '[{"name": "Indian Stand-up Comedy Network", "url": "https://facebook.com"}, {"name": "Comedy Writers India", "url": "https://linkedin.com"}]'::jsonb,
  ARRAY['Canvas Laugh Club', 'OML Entertainment', 'East India Comedy', 'Comedy Store India'],
  TRUE
),

-- 20. Academic Researcher (PhD Track)
(
  'Education & Training',
  'Academic Researcher (PhD Track)',
  'academic-researcher-phd',
  'Advance human knowledge — through rigorous research in the humanities and social sciences.',
  'For UPSC aspirants with a deep passion for their subject, a PhD is a natural next step. India''s UGC-funded research fellowships (JRF) pay well enough to live on, and the academic job market rewards those with UPSC-level depth of knowledge. International postdoc opportunities are also growing for Indian scholars.',
  '₹4 LPA', '₹14 LPA', '₹28 LPA',
  ARRAY['Intellectual freedom', 'Academic conferences', 'International collaborations', 'Government research funding'],
  'Expand the frontiers of knowledge in disciplines critical to India''s development — history, political science, economics, sociology, and more.',
  'Interact with global academics, attend international conferences, publish in top journals, advise government bodies.',
  'Master''s degree required; NET-JRF for funded PhD in India',
  ARRAY['Research methodology', 'Academic writing', 'Critical analysis', 'Literature review', 'Statistical analysis', 'Grant writing', 'Presenting research'],
  'UPSC optional subject depth is the core advantage. GS preparation builds broad social science foundation. Research aptitude from Mains answer writing. Overlap Score: 80%',
  4, 'Moderate',
  '[{"title": "Research Methods in Social Sciences", "provider": "NPTEL", "url": "https://nptel.ac.in", "free": true}, {"title": "Academic Writing in English", "provider": "Coursera (Duke)", "url": "https://www.coursera.org/specializations/academic-english", "free": false}]'::jsonb,
  ARRAY['UGC-NET with JRF', 'PhD Degree (mandatory)', 'GRE (for international programs)'],
  ARRAY['Write a 3000-word research proposal on an original thesis topic', 'Submit a paper to a UGC CARE-listed journal', 'Present at one academic seminar or conference'],
  '[{"week": 1, "focus": "Research gap identification", "tasks": ["Identify 3 potential research questions from your UPSC preparation", "Read 10 recent journal articles in your field using JSTOR/Google Scholar", "Study PhD programs at JNU, DU, Hyderabad University, and IITs"]}, {"week": 2, "focus": "JRF preparation", "tasks": ["Register for UGC-NET with JRF option", "Study UGC-NET research methodology paper (Paper 1) deeply", "Write a 1000-word research statement for your proposed PhD topic"]}, {"week": 3, "focus": "Applications", "tasks": ["Research PhD programs: JNU, Hyderabad University, TISS, Jamia, IITs", "Study Ashoka and Azim Premji University for liberal arts research", "Contact potential supervisors by email with your research statement"]}, {"week": 4, "focus": "Strengthen application", "tasks": ["Write an abstract for a paper you could submit to a journal", "Attend a virtual academic conference in your field", "Take GRE if planning US/UK PhD applications"]}]'::jsonb,
  '₹0 (JRF stipend covers living costs; ₹1,00,000+ for international applications)',
  'Apply to JNU, Hyderabad University, TISS, Delhi University, Ashoka University. For international programs, target Oxford, Cambridge, and US universities with funded PhD programs.',
  '[{"title": "PhD in India After UPSC", "channel": "Academic Career India", "url": "https://youtube.com"}, {"title": "Research Methodology Simplified", "channel": "Research Scholar India", "url": "https://youtube.com"}]'::jsonb,
  '[{"title": "The Research Lab India", "platform": "Spotify", "url": "https://spotify.com"}]'::jsonb,
  '[{"name": "PhD Scholars India", "url": "https://facebook.com"}, {"name": "JNU Research Network", "url": "https://linkedin.com"}]'::jsonb,
  ARRAY['UGC (University Grants Commission)', 'ICSSR (Indian Council of Social Science Research)'],
  TRUE
),

-- 21. UX Researcher
(
  'Data, Analytics & Tech-Adjacent',
  'UX Researcher',
  'ux-researcher',
  'Understand how humans interact with technology — and make products that actually work.',
  'UX Research is one of the most accessible tech careers for non-programmers. It''s fundamentally about understanding human behavior — through interviews, surveys, and observation. UPSC aspirants who studied sociology, anthropology, or public administration are naturally skilled UX researchers. India''s product companies are hiring aggressively.',
  '₹10 LPA', '₹22 LPA', '₹55 LPA',
  ARRAY['Remote-friendly', 'Work on products used by millions', 'High pay without coding', 'Creative analytical work'],
  'Ensure that India''s digital products actually work for ordinary citizens — including those in tier-2/3 cities and rural areas.',
  'Work with product managers, designers, and engineers at top tech companies. Present research to leadership.',
  'Graduate in any field; psychology/sociology background is an advantage',
  ARRAY['Qualitative research', 'Interviewing', 'Survey design', 'Synthesis and pattern recognition', 'Figma (basic)', 'Usability testing', 'Storytelling with data'],
  'Sociology and Anthropology optionals are directly applicable. Research methodology from UPSC preparation transfers well. Overlap Score: 65%',
  2, 'High',
  '[{"title": "Google UX Design Certificate", "provider": "Coursera (Google)", "url": "https://www.coursera.org/professional-certificates/google-ux-design", "free": false}, {"title": "UX Research Methods", "provider": "Interaction Design Foundation", "url": "https://www.interaction-design.org/courses/user-research", "free": false}]'::jsonb,
  ARRAY['Google UX Design Certificate', 'NNGroup UX Certification', 'IxDF UX Research Certification'],
  ARRAY['Conduct a full usability study on a government app (e.g., DigiLocker) and write a report', 'Create a UX research portfolio with 3 case studies hosted on Notion', 'Run a competitive analysis for a product in your chosen domain'],
  '[{"week": 1, "focus": "UXR basics", "tasks": ["Read ''The User Experience Team of One'' by Leah Buley", "Watch Nielsen Norman Group free YouTube videos on UX research methods", "Complete Google UX Design Certificate (free via Coursera with audit)"]}, {"week": 2, "focus": "Practice research", "tasks": ["Conduct 5 user interviews about a digital product you use (WhatsApp, Google Pay)", "Synthesize findings into an affinity diagram", "Write up a research report with key insights and recommendations"]}, {"week": 3, "focus": "Tools", "tasks": ["Learn Figma basics (free)", "Practice with Dovetail or Notion for research synthesis", "Create a simple usability test script and run it with 3 friends"]}, {"week": 4, "focus": "Apply", "tasks": ["Build a UXR portfolio with 2 case studies on Notion", "Apply to Flipkart, Swiggy, PhonePe, Razorpay, Zoho for UXR roles", "Apply to Google, Microsoft India — they hire researchers from humanities backgrounds"]}]'::jsonb,
  '₹5,000–₹30,000 (certifications)',
  'Apply via LinkedIn Jobs, AngelList India, IIMJobs. Target Flipkart, Swiggy, PhonePe, Razorpay, Zoho, Google India, Microsoft India.',
  '[{"title": "UX Research for Beginners", "channel": "AJ&Smart", "url": "https://youtube.com/ajsmart"}, {"title": "Breaking into UX from Non-Tech Background", "channel": "NNGroup", "url": "https://youtube.com/nngroup"}]'::jsonb,
  '[{"title": "UI Breakfast Podcast", "platform": "Spotify", "url": "https://spotify.com"}]'::jsonb,
  '[{"name": "UX Researchers India", "url": "https://linkedin.com"}, {"name": "UX India Community", "url": "https://linkedin.com"}]'::jsonb,
  ARRAY['IxDF (Interaction Design Foundation)', 'NNGroup India', 'UX India'],
  TRUE
)
ON CONFLICT (slug) DO NOTHING;
